import { Player } from "@/types"

export const yourTeam: Player[] = [
  {
    id: "1",
    name: "Josh Allen",
    position: "QB",
    points: 24.8,
    avatar: "🏈",
    team: "BUF",
    stats: {
      passingYards: 312,
      touchdowns: 3,
      interceptions: 1,
    },
    formationPosition: { x: 50, y: 75 },
  },
  {
    id: "2",
    name: "Christian McCaffrey",
    position: "RB",
    points: 22.4,
    avatar: "🏃‍♂️",
    team: "SF",
    stats: {
      rushingYards: 102,
      touchdowns: 1,
      fumbles: 0,
    },
    formationPosition: { x: 30, y: 90 },
  },
    {
        id: "3",
        name: "Tyrone Tracy",
        position: "RB",
        points: 21.2,
        avatar: "🏃‍♂️",
        team: "NYG",
        stats: {
        receivingYards: 88,
        touchdowns: 1,
        receptions: 6,
        targets: 9,
        },
        formationPosition: { x: 70, y: 70 },
    },
  {
    id: "4",
    name: "Tyreek Hill",
    position: "WR",
    points: 18.5,
    avatar: "🦅",
    team: "MIA",
    stats: {
      receivingYards: 120,
      touchdowns: 1,
      receptions: 8,
      targets: 10,
    },
    formationPosition: { x: 70, y: 80 },
  },
  {
    id: "5",
    name: "Stefon Diggs",
    position: "WR",
    points: 19.6,
    avatar: "🧢",
    team: "BUF",
    stats: {
      receivingYards: 96,
      touchdowns: 1,
      receptions: 7,
    },
    formationPosition: { x: 70, y: 90 },
  },
]

export const opponentTeam: Player[] = [
  {
    id: "101",
    name: "Patrick Mahomes",
    position: "QB",
    points: 26.3,
    avatar: "🏈",
    team: "KC",
    stats: {
      passingYards: 334,
      touchdowns: 4,
      interceptions: 0,
    },
    formationPosition: { x: 50, y: 25 },
  },
  {
    id: "102",
    name: "Derrick Henry",
    position: "RB",
    points: 20.2,
    avatar: "🛡️",
    team: "TEN",
    stats: {
      rushingYards: 118,
      touchdowns: 1,
      fumbles: 1,
    },
    formationPosition: { x: 30, y: 10 },
  },
    {
        id: "103",
        name: "Davante Adams",
        position: "WR",
        points: 21.5,
        avatar: "🦁",
        team: "LV",
        stats: {
        receivingYards: 105,
        touchdowns: 1,
        receptions: 9,
        targets: 12,
        },
        formationPosition: { x: 70, y: 20 },
    },
  {
    id: "104",
    name: "Tyreek Hill",
    position: "WR",
    points: 23.8,
    avatar: "🔥",
    team: "MIA",
    stats: {
      receivingYards: 110,
      touchdowns: 2,
      receptions: 8,
    },
    formationPosition: { x: 70, y: 10 },
  },
    {
        id: "105",
        name: "Travis Kelce",
        position: "TE",
        points: 18.9,
        avatar: "👑",
        team: "KC",
        stats: {
        receivingYards: 85,
        touchdowns: 1,
        receptions: 6,
        },
        formationPosition: { x: 70, y: 30 },
    },
]

